AllCops:
  Exclude:
    # ACTIONS
    - app/actions/banish_project_action.rb
    - app/actions/import_missing_payables_action.rb

    # CONTROLLERS
    - app/controllers/admin/balance_transactions_controller.rb
    - app/controllers/admin/balance_transfers_controller.rb
    - app/controllers/admin/base_controller.rb
    - app/controllers/admin/contributions_controller.rb
    - app/controllers/admin/financials_controller.rb
    - app/controllers/admin/projects_controller.rb
    - app/controllers/admin/reports/contribution_reports_controller.rb
    - app/controllers/admin/subscription_payments_controller.rb
    - app/controllers/api_tokens_controller.rb
    - app/controllers/application_controller.rb
    - app/controllers/auto_complete_cities_controller.rb
    - app/controllers/auto_complete_projects_controller.rb
    - app/controllers/categories/subscriptions_controller.rb
    - app/controllers/concerns/admin/reports_handler.rb
    - app/controllers/concerns/analytics_helpers_handler.rb
    - app/controllers/concerns/exception_handler.rb
    - app/controllers/concerns/konduto_handler.rb
    - app/controllers/concerns/locale_handler.rb
    - app/controllers/concerns/old_browser_checker.rb
    - app/controllers/concerns/pixel_helpers_handler.rb
    - app/controllers/concerns/social_helpers_handler.rb
    - app/controllers/goals_controller.rb
    - app/controllers/home/banners_controller.rb
    - app/controllers/mail_marketing_users_controller.rb
    - app/controllers/notifications_controller.rb
    - app/controllers/omniauth_callbacks_controller.rb
    - app/controllers/passwords_controller.rb
    - app/controllers/projects/contributions_controller.rb
    - app/controllers/projects/integrations_controller.rb
    - app/controllers/projects/posts_controller.rb
    - app/controllers/projects/project_fiscal_data_controller.rb
    - app/controllers/projects/project_report_exports_controller.rb
    - app/controllers/projects_controller.rb
    - app/controllers/reports/contribution_reports_for_project_owners_controller.rb
    - app/controllers/rewards_controller.rb
    - app/controllers/sessions_controller.rb
    - app/controllers/static_controller.rb
    - app/controllers/surveys_controller.rb
    - app/controllers/users/credit_cards_controller.rb
    - app/controllers/users_controller.rb
    - app/controllers/zendesk_sessions_controller.rb

    # DECORATORS
    - app/decorators/category_decorator.rb
    - app/decorators/contribution_detail_decorator.rb
    - app/decorators/project_decorator.rb
    - app/decorators/project_post_decorator.rb
    - app/decorators/reward_decorator.rb
    - app/decorators/user_decorator.rb

    # MAILERS
    - app/mailers/notifier.rb

    # MODELS
    - app/models/address.rb
    - app/models/antifraud_analysis.rb
    - app/models/api_wrapper.rb
    - app/models/authorization.rb
    - app/models/balance_transaction.rb
    - app/models/balance_transfer.rb
    - app/models/balance_transfer_transition.rb
    - app/models/bank.rb
    - app/models/bank_account.rb
    - app/models/banned_ip.rb
    - app/models/blacklist_document.rb
    - app/models/category.rb
    - app/models/category_follower.rb
    - app/models/category_total.rb
    - app/models/city.rb
    - app/models/common_wrapper.rb
    - app/models/concerns/contribution/custom_validators.rb
    - app/models/concerns/contribution/state_machine_handler.rb
    - app/models/concerns/payment/payment_engine_handler.rb
    - app/models/concerns/payment/request_refund_handler.rb
    - app/models/concerns/project/all_or_nothing_state_validator.rb
    - app/models/concerns/project/base_validator.rb
    - app/models/concerns/project/custom_validators.rb
    - app/models/concerns/project/video_handler.rb
    - app/models/concerns/shared/bank_account_helper.rb
    - app/models/concerns/shared/chart_handler.rb
    - app/models/concerns/shared/common_wrapper.rb
    - app/models/concerns/shared/materialized_view.rb
    - app/models/concerns/shared/queued.rb
    - app/models/concerns/shared/state_machine_helpers.rb
    - app/models/concerns/shared/video_handler.rb
    - app/models/concerns/users/custom_validators.rb
    - app/models/concerns/users/omniauth_handler.rb
    - app/models/contribution.rb
    - app/models/contribution_detail.rb
    - app/models/contribution_report.rb
    - app/models/contribution_reports_for_project_owner.rb
    - app/models/country.rb
    - app/models/credit_card.rb
    - app/models/direct_message.rb
    - app/models/donation.rb
    - app/models/flexible_project.rb
    - app/models/gateway_balance_operation.rb
    - app/models/gateway_payable.rb
    - app/models/gateway_payment.rb
    - app/models/goal.rb
    - app/models/home_banner.rb
    - app/models/login_activity.rb
    - app/models/mail_marketing_list.rb
    - app/models/mail_marketing_user.rb
    - app/models/notification.rb
    - app/models/oauth_provider.rb
    - app/models/origin.rb
    - app/models/payment.rb
    - app/models/payment_log.rb
    - app/models/payment_notification.rb
    - app/models/payment_transfer.rb
    - app/models/post_reward.rb
    - app/models/project.rb
    - app/models/project_budget.rb
    - app/models/project_cancelation.rb
    - app/models/project_error.rb
    - app/models/project_financial.rb
    - app/models/project_fiscal_data.rb
    - app/models/project_fiscal_inform.rb
    - app/models/project_integration.rb
    - app/models/project_metric_storage.rb
    - app/models/project_post.rb
    - app/models/project_reminder.rb
    - app/models/project_report.rb
    - app/models/project_report_export.rb
    - app/models/project_score_storage.rb
    - app/models/project_total.rb
    - app/models/project_transition.rb
    - app/models/public_tag.rb
    - app/models/rdevent.rb
    - app/models/redactor_rails/asset.rb
    - app/models/redactor_rails/picture.rb
    - app/models/reward.rb
    - app/models/reward_metric_storage.rb
    - app/models/sendgrid_event.rb
    - app/models/shared.rb
    - app/models/shipping_fee.rb
    - app/models/social_follower.rb
    - app/models/state.rb
    - app/models/statistics.rb
    - app/models/subscription.rb
    - app/models/subscription_monthly_report_for_project_owner.rb
    - app/models/subscription_payment.rb
    - app/models/subscription_payment_transition.rb
    - app/models/subscription_project.rb
    - app/models/subscription_report_for_project_owner.rb
    - app/models/subscription_transition.rb
    - app/models/survey.rb
    - app/models/survey_address_answer.rb
    - app/models/survey_multiple_choice_question.rb
    - app/models/survey_multiple_choice_question_answer.rb
    - app/models/survey_open_question.rb
    - app/models/survey_open_question_answer.rb
    - app/models/survey_question_choice.rb
    - app/models/tag.rb
    - app/models/tagging.rb
    - app/models/unsubscribe.rb
    - app/models/user.rb
    - app/models/user_action_broadcast.rb
    - app/models/user_admin_role.rb
    - app/models/user_credit.rb
    - app/models/user_feed.rb
    - app/models/user_follow.rb
    - app/models/user_friend.rb
    - app/models/user_link.rb
    - app/models/user_total.rb
    - app/models/user_transfer.rb
    - app/models/users.rb

    # OBSERVERS
    - app/observers/contribution_observer.rb
    - app/observers/flexible_project_observer.rb
    - app/observers/payment_observer.rb
    - app/observers/project_observer.rb
    - app/observers/project_post_observer.rb
    - app/observers/subscription_project_observer.rb
    - app/observers/survey_observer.rb
    - app/observers/user_observer.rb

    # POLICIES
    - app/policies/admin_balance_policy.rb
    - app/policies/admin_policy.rb
    - app/policies/application_policy.rb
    - app/policies/bank_account_policy.rb
    - app/policies/contribution_policy.rb
    - app/policies/credit_card_policy.rb
    - app/policies/flexible_project_policy.rb
    - app/policies/goal_policy.rb
    - app/policies/home_banner_policy.rb
    - app/policies/project_fiscal_data_policy.rb
    - app/policies/project_integration_policy.rb
    - app/policies/project_policy.rb
    - app/policies/project_post_policy.rb
    - app/policies/reward_policy.rb
    - app/policies/subscription_project_policy.rb
    - app/policies/survey_policy.rb
    - app/policies/user_policy.rb

    # STATE MACHINE
    - app/state_machine/aon_project_machine.rb
    - app/state_machine/balance_transfer_machine.rb
    - app/state_machine/flex_project_machine.rb
    - app/state_machine/sub_project_machine.rb

    # UPLOADERS
    - app/uploaders/cover_uploader.rb
    - app/uploaders/image_uploader.rb
    - app/uploaders/profile_uploader.rb
    - app/uploaders/project_uploader.rb
    - app/uploaders/redactor_rails_picture_uploader.rb
    - app/uploaders/report_uploader.rb
    - app/uploaders/reward_uploader.rb
    - app/uploaders/user_uploader.rb

    # WORKERS
    - app/workers/banish_project_worker.rb
    - app/workers/campaign_finisher_worker.rb
    - app/workers/direct_refund_worker.rb
    - app/workers/email_worker.rb
    - app/workers/facebook_scrape_reload_worker.rb
    - app/workers/fb_friend_collector_worker.rb
    - app/workers/fb_page_collector_worker.rb
    - app/workers/pending_contribution_worker.rb
    - app/workers/project_base_worker.rb
    - app/workers/project_downloader_worker.rb
    - app/workers/project_metric_storage_refresh_worker.rb
    - app/workers/project_post_worker.rb
    - app/workers/project_report_export_worker.rb
    - app/workers/project_score_storage_refresh_worker.rb
    - app/workers/reward_metric_storage_refresh_worker.rb
    - app/workers/sendgrid_sync_worker.rb
    - app/workers/transfer_worker.rb
    - app/workers/user_broadcast_worker.rb

    # LIB
    - lib/blog.rb
    - lib/calendar.rb
    - lib/payment_engines.rb
    - lib/payment_engines/interface.rb
    - lib/sandbox_mail_interceptor.rb
    - lib/sanitize_script_tag.rb
    - lib/sendgrid_event_processor.rb
    - lib/subdomain_constraint.rb
    - lib/tasks/aws.rake
    - lib/tasks/balance_transaction.rake
    - lib/tasks/balance_transfer.rake
    - lib/tasks/common.rake
    - lib/tasks/common/generate_fdw.rake
    - lib/tasks/config.rake
    - lib/tasks/cron.rake
    - lib/tasks/db_seed.rake
    - lib/tasks/dev_seed/default_settings.rake
    - lib/tasks/dev_seed/dummy_data.rake
    - lib/tasks/dispatch_project_metric_storage_refresh_task.rake
    - lib/tasks/dispatch_reward_metric_storage_refresh_task.rake
    - lib/tasks/import_missing_payables_task.rake
    - lib/tasks/listen.rake
    - lib/tasks/migrate_payment_data.rake
    - lib/tasks/migrate_thumbnails.rake
    - lib/tasks/projects.rake
    - lib/tasks/refresh_contribuition_rewards_metrics_task.rake
    - lib/tasks/refresh_payment_rewards_metrics_task.rake
    - lib/tasks/refresh_subscription_rewards_metrics_task.rake
    - lib/tasks/send_old_posts_to_tumblr.rake
    - lib/tasks/sendgrid.rake
    - lib/tasks/sync_deleted_projects_task.rake
    - lib/tasks/users.rake
    - lib/tasks/verify_pagarme_transactions.rake
    - lib/transfeera/authorization.rb
    - lib/transfeera/bank_account_validator.rb

    # DB/SEEDS
    - db/seeds/my-seeds-local.example.rb
    - db/seeds/add-users.rb

    # CONFIG
    - config/initializers/simple_form/validation_text.rb
    - config/initializers/simple_form/preppend_input_text.rb
    - config/initializers/simple_form/append_input_text.rb
    - config/initializers/simple_form.rb
    - config/initializers/pagarme.rb
    - config/initializers/devise.rb

    # SPEC
    - spec/config/initializers/secret_token_spec.rb

    - spec/controllers/admin/balance_transactions_controller_spec.rb
    - spec/controllers/admin/balance_transfers_controller_spec.rb
    - spec/controllers/admin/contributions_controller_spec.rb
    - spec/controllers/admin/financials_controller_spec.rb
    - spec/controllers/admin/projects_controller_spec.rb
    - spec/controllers/api_tokens_controller_spec.rb
    - spec/controllers/application_controller_spec.rb
    - spec/controllers/auto_complete_projects_controller_spec.rb
    - spec/controllers/categories/subscriptions_controller_spec.rb
    - spec/controllers/concerns/social_helpers_handler_spec.rb
    - spec/controllers/goals_controller_spec.rb
    - spec/controllers/home/banners_controller_spec.rb
    - spec/controllers/mail_marketing_users_controller_spec.rb
    - spec/controllers/notifications_controller_spec.rb
    - spec/controllers/omniauth_callbacks_controller_spec.rb
    - spec/controllers/projects/contributions_controller_spec.rb
    - spec/controllers/projects/integrations_controller_spec.rb
    - spec/controllers/projects/posts_controller_spec.rb
    - spec/controllers/projects/project_report_exports_controller_spec.rb
    - spec/controllers/projects_controller_spec.rb
    - spec/controllers/rewards_controller_spec.rb
    - spec/controllers/static_controller_spec.rb
    - spec/controllers/users/credit_cards_controller_spec.rb
    - spec/controllers/users_controller_spec.rb

    - spec/decorators/contribution_detail_decorator_spec.rb
    - spec/decorators/project_decorator_spec.rb
    - spec/decorators/project_post_decorator_spec.rb
    - spec/decorators/reward_decorator_spec.rb
    - spec/decorators/user_decorator_spec.rb

    - spec/lib/blog_spec.rb
    - spec/lib/payment_engines_spec.rb
    - spec/lib/tasks/refresh_contribution_rewards_metrics_task_spec.rb
    - spec/lib/tasks/refresh_payment_rewards_metrics_task_spec.rb
    - spec/lib/tasks/refresh_subscription_rewards_metrics_task_spec.rb

    - spec/mailers/notifier_spec.rb

    - spec/models/address_spec.rb
    - spec/models/api_wrapper_spec.rb
    - spec/models/authorizations_spec.rb
    - spec/models/balance_transaction_spec.rb
    - spec/models/balance_transfer_spec.rb
    - spec/models/bank_account_spec.rb
    - spec/models/bank_spec.rb
    - spec/models/blacklist_document_spec.rb
    - spec/models/category_follower_spec.rb
    - spec/models/category_spec.rb
    - spec/models/concerns/contribution/custom_validators_spec.rb
    - spec/models/concerns/payment/payment_engine_handler_spec.rb
    - spec/models/concerns/project/all_or_nothing_state_validator_spec.rb
    - spec/models/concerns/project/base_validator_spec.rb
    - spec/models/concerns/project/custom_validators_spec.rb
    - spec/models/concerns/project/video_handler_spec.rb
    - spec/models/concerns/shared/video_handler_spec.rb
    - spec/models/concerns/users/custom_validators_spec.rb
    - spec/models/concerns/users/omniauth_handler_spec.rb
    - spec/models/contribution_detail_spec.rb
    - spec/models/contribution_report_spec.rb
    - spec/models/contribution_reports_for_project_owner_spec.rb
    - spec/models/contribution_spec.rb
    - spec/models/credit_card_spec.rb
    - spec/models/flexible_project_spec.rb
    - spec/models/home_banner_spec.rb
    - spec/models/login_activity_spec.rb
    - spec/models/mail_marketing_list_spec.rb
    - spec/models/mail_marketing_user_spec.rb
    - spec/models/notification_spec.rb
    - spec/models/oauth_provider_spec.rb
    - spec/models/origin_spec.rb
    - spec/models/payment_log_spec.rb
    - spec/models/payment_notification_spec.rb
    - spec/models/payment_spec.rb
    - spec/models/payment_transfer_spec.rb
    - spec/models/post_reward_spec.rb
    - spec/models/project_cancelation_spec.rb
    - spec/models/project_financial_spec.rb
    - spec/models/project_integration_spec.rb
    - spec/models/project_metric_storage_spec.rb
    - spec/models/project_post_spec.rb
    - spec/models/project_reminder_spec.rb
    - spec/models/project_report_export_spec.rb
    - spec/models/project_score_storage_spec.rb
    - spec/models/project_spec.rb
    - spec/models/project_total_spec.rb
    - spec/models/project_transition_spec.rb
    - spec/models/rdevent_spec.rb
    - spec/models/reward_metric_storage_spec.rb
    - spec/models/reward_spec.rb
    - spec/models/state_spec.rb
    - spec/models/statistics_spec.rb
    - spec/models/subscription_payment_spec.rb
    - spec/models/subscription_spec.rb
    - spec/models/unsubscribe_spec.rb
    - spec/models/user_action_broadcast_spec.rb
    - spec/models/user_admin_role_spec.rb
    - spec/models/user_follow_spec.rb
    - spec/models/user_link_spec.rb
    - spec/models/user_spec.rb
    - spec/models/user_total_spec.rb

    - spec/observers/contribution_observer_spec.rb
    - spec/observers/payment_observer_spec.rb
    - spec/observers/project_observer_spec.rb
    - spec/observers/project_post_observer_spec.rb
    - spec/observers/user_observer_spec.rb

    - spec/policies/admin_policy_spec.rb
    - spec/policies/contribution_policy_spec.rb
    - spec/policies/project_policy_spec.rb
    - spec/policies/project_post_policy_spec.rb
    - spec/policies/reward_policy_spec.rb
    - spec/policies/user_policy_spec.rb

    - spec/state_machine/aon_project_machine_spec.rb
    - spec/state_machine/flex_project_machine_spec.rb

    - spec/uploaders/image_uploader_spec.rb
    - spec/uploaders/project_uploader_spec.rb
    - spec/uploaders/user_uploader_spec.rb

    - spec/workers/banish_project_worker_spec.rb
    - spec/workers/direct_refund_worker_spec.rb
    - spec/workers/pending_contribution_worker_spec.rb
    - spec/workers/project_downloader_worker_spec.rb
    - spec/workers/project_metric_storage_refresh_worker_spec.rb
    - spec/workers/project_post_worker_spec.rb
    - spec/workers/reward_metric_storage_refresh_worker_spec.rb
    - spec/workers/sendgrid_sync_worker_spec.rb

    - spec/factories/addresses_factories.rb
    - spec/factories/authorizations_factories.rb
    - spec/factories/balance_transactions_factories.rb
    - spec/factories/balance_transfers_factories.rb
    - spec/factories/bank_accounts_factories.rb
    - spec/factories/banks_factories.rb
    - spec/factories/blacklist_documents_factories.rb
    - spec/factories/categories_factories.rb
    - spec/factories/category_followers_factories.rb
    - spec/factories/cities_factories.rb
    - spec/factories/contributions_factories.rb
    - spec/factories/countries_factories.rb
    - spec/factories/credit_cards_factories.rb
    - spec/factories/donations_factories.rb
    - spec/factories/flexibles_projects_factories.rb
    - spec/factories/goals_factories.rb
    - spec/factories/home_banners_factories.rb
    - spec/factories/mail_marketing_lists_factories.rb
    - spec/factories/mail_marketing_users_factories.rb
    - spec/factories/notifications_factories.rb
    - spec/factories/oauth_providers_factories.rb
    - spec/factories/origins_factories.rb
    - spec/factories/payment_notifications_factories.rb
    - spec/factories/payments_factories.rb
    - spec/factories/post_rewards_factories.rb
    - spec/factories/project_budgets_factories.rb
    - spec/factories/project_cancelations_factories.rb
    - spec/factories/project_integrations_factories.rb
    - spec/factories/project_invites_factories.rb
    - spec/factories/project_notifications_factories.rb
    - spec/factories/project_posts_factories.rb
    - spec/factories/project_reminders_factories.rb
    - spec/factories/project_report_exports_factories.rb
    - spec/factories/project_transitions_factories.rb
    - spec/factories/projects_factories.rb
    - spec/factories/rewards_factories.rb
    - spec/factories/shared/sequences.rb
    - spec/factories/shipping_fees_factories.rb
    - spec/factories/states_factories.rb
    - spec/factories/subscription_projects_factories.rb
    - spec/factories/unsubscribes_factories.rb
    - spec/factories/user_admin_roles_factories.rb
    - spec/factories/user_follows_factories.rb
    - spec/factories/user_links_factories.rb
    - spec/factories/users_factories.rb
    - spec/factories/users_oauth_providers_factories.rb

    - spec/support/helpers/project_spec_helpers.rb
    - spec/support/hooks.rb
