require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from: ./.rubocop-disable-legacy.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/routes.rb'
    - 'node_modules/**/*'
    - 'catarse.js/**/*'
    - 'engines/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Rails/Delegate:
  Enabled: false

Rails/UnknownEnv:
  Environments: ['production', 'test', 'development', 'sandbox', 'cucumber']

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  AutoCorrect: true

Style/SymbolProc:
  AllowMethodsWithArguments: true

Style/UnlessLogicalOperators:
  EnforcedStyle: forbid_logical_operators
